ControllerBlueprintsApplicationTest-Fixed testcase
testConfigModelFailure testcase failed with below error,

Error: expected 400 but was 200.

This was because the url was not set to proper endpoint that returns
staus not found. Changed the endpoint to proper url.

Issue-ID: CCSDK-552
Change-Id: I4b9e1081f67639ee9bc942d1f4eae30280d8a66d
Signed-off-by: Arundathi Patil <arundpil@in.ibm.com>